//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordhauLoadoutImport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Helmets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Helmets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MordhauLoadoutImport.Helmets", typeof(Helmets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peasant Cap.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Templar.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointy Templar.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bascinet Raised Visor.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bascinet Visor.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Helmet.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbute Visor.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbute Raised.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbute.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Mantle.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Coif.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hood.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded Coif.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slitted Kettle.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peasant Hat.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klappvisier.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klappvisier Up.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvisored Klappvisier.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian Klappvisier.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klappvisier Italian Up.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norman Casque.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised Gothic Armet.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish Kettle.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domed Armet.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domed Armet Raised.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Armet.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Armet Raised.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Armet.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Armet Raised.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedge Armet.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedge Armet Raised.
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sallet Bevor.
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Sallet Bevor.
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kettle.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Sallet Raised Visor.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Sallet.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown Visor.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greathelm.
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greathelm Band.
        /// </summary>
        internal static string _45 {
            get {
                return ResourceManager.GetString("_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greathelm Cloak.
        /// </summary>
        internal static string _46 {
            get {
                return ResourceManager.GetString("_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Greathelm.
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Greathelm Band.
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Greathelm Cloak.
        /// </summary>
        internal static string _49 {
            get {
                return ResourceManager.GetString("_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eisenhut.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hounskull.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hounskull Raised.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hounskull no visor.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maille Hood Lowered.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maille Hood Spiked Lowered.
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archers Cap.
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archers Cap Feather.
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Kettle.
        /// </summary>
        internal static string _57 {
            get {
                return ResourceManager.GetString("_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Kettle Raised.
        /// </summary>
        internal static string _58 {
            get {
                return ResourceManager.GetString("_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaperone Hat.
        /// </summary>
        internal static string _59 {
            get {
                return ResourceManager.GetString("_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Top.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landsknecht Hat Feather.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landsknecht Hat.
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgonet Buffet.
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgonet No Buffet.
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conic Facemask.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Facemask.
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spangenhelm stripped.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spangenhelm.
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norman Casque No Nasal Guard.
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanderers Hood.
        /// </summary>
        internal static string _69 {
            get {
                return ResourceManager.GetString("_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sallet Raised Visor.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Hood.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Barbute Visor.
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painted Barbute Raised.
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armet Plume.
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sallet.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viking Helmet.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
    }
}
