//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MordhauLoadoutImport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Wearables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wearables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MordhauLoadoutImport.Wearables", typeof(Wearables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peasant Cap.
        /// </summary>
        internal static string _1_1 {
            get {
                return ResourceManager.GetString("_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hood.
        /// </summary>
        internal static string _1_2 {
            get {
                return ResourceManager.GetString("_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishops Mantle.
        /// </summary>
        internal static string _2_1 {
            get {
                return ResourceManager.GetString("_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padded Hood.
        /// </summary>
        internal static string _2_2 {
            get {
                return ResourceManager.GetString("_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peasant Shirt.
        /// </summary>
        internal static string _3_1 {
            get {
                return ResourceManager.GetString("_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather Armor.
        /// </summary>
        internal static string _3_2 {
            get {
                return ResourceManager.GetString("_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Mantle.
        /// </summary>
        internal static string _4_1 {
            get {
                return ResourceManager.GetString("_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Pauldrons.
        /// </summary>
        internal static string _4_2 {
            get {
                return ResourceManager.GetString("_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string _5_1 {
            get {
                return ResourceManager.GetString("_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brigandine Arms.
        /// </summary>
        internal static string _5_2 {
            get {
                return ResourceManager.GetString("_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Gloves.
        /// </summary>
        internal static string _6_1 {
            get {
                return ResourceManager.GetString("_6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chainmail Mittens.
        /// </summary>
        internal static string _6_2 {
            get {
                return ResourceManager.GetString("_6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string _7_1 {
            get {
                return ResourceManager.GetString("_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothic Skirt.
        /// </summary>
        internal static string _7_2 {
            get {
                return ResourceManager.GetString("_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunters Hosen.
        /// </summary>
        internal static string _8_1 {
            get {
                return ResourceManager.GetString("_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calf Guard Hosen.
        /// </summary>
        internal static string _8_2 {
            get {
                return ResourceManager.GetString("_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laced Boots.
        /// </summary>
        internal static string _9_1 {
            get {
                return ResourceManager.GetString("_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointy Leather Shoes ?.
        /// </summary>
        internal static string _9_2 {
            get {
                return ResourceManager.GetString("_9_2", resourceCulture);
            }
        }
    }
}
